"""Report export system for the Single-Cell Intelligence Agent.

Supports four export formats:
  - export_markdown()      -- structured analysis Markdown report
  - export_json()          -- machine-readable JSON
  - export_pdf()           -- styled PDF via ReportLab Platypus
  - export_fhir_r4()       -- FHIR R4 DiagnosticReport Bundle

Plus specialised report generators:
  - export_cell_type_report()   -- cell type annotation summary
  - export_tme_report()         -- TME profiling report
  - export_drug_response_report() -- drug response prediction report
  - export_anndata_metadata()   -- AnnData-compatible metadata dict

Author: Adam Jones
Date: March 2026
"""

from __future__ import annotations

import io
import json
import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Union

from .models import (
    CellTypeAnnotation,
    DrugResponsePrediction,
    EvidenceLevel,
    SCWorkflowType,
    SeverityLevel,
    TMEProfile,
    WorkflowResult,
)

logger = logging.getLogger(__name__)

VERSION = "1.0.0"


# ===================================================================
# SEVERITY COLOUR MAP
# ===================================================================

SEVERITY_COLORS: Dict[SeverityLevel, str] = {
    SeverityLevel.LOW:            "#2ECC71",  # green
    SeverityLevel.INFORMATIONAL:  "#3498DB",  # blue
    SeverityLevel.MODERATE:       "#F39C12",  # orange
    SeverityLevel.HIGH:           "#E74C3C",  # red
    SeverityLevel.CRITICAL:       "#8E44AD",  # purple
}


# ===================================================================
# REPORT TEMPLATES (Markdown fragments)
# ===================================================================

REPORT_TEMPLATES: Dict[str, str] = {
    "cell_type": (
        "# Cell Type Annotation Report\n\n"
        "**Sample ID:** {sample_id}  \n"
        "**Report Type:** Cell Type Annotation  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "tme": (
        "# Tumor Microenvironment Profile Report\n\n"
        "**Sample ID:** {sample_id}  \n"
        "**Report Type:** TME Profiling  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "drug_response": (
        "# Drug Response Prediction Report\n\n"
        "**Sample ID:** {sample_id}  \n"
        "**Report Type:** Drug Response  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
    "workflow": (
        "# Single-Cell Analysis Report\n\n"
        "**Report Type:** {workflow_type} Workflow  \n"
        "**Generated:** {timestamp}  \n"
        "**Agent Version:** {version}\n\n"
        "---\n\n"
    ),
}

_DISCLAIMER = (
    "\n\n---\n\n"
    "> **Disclaimer:** This report is generated by the HCLS AI Factory "
    "Single-Cell Intelligence Agent for research and clinical decision-support "
    "purposes only. It does not constitute medical advice and must be reviewed "
    "by qualified specialists before any clinical action is taken. All "
    "predictions and classifications are computational estimates.\n"
)


# ===================================================================
# HELPER FUNCTIONS
# ===================================================================


def _now_iso() -> str:
    """Return the current UTC timestamp in ISO-8601 format."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _now_display() -> str:
    """Return a human-friendly UTC timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _severity_indicator(severity: SeverityLevel) -> str:
    """Return a text indicator for severity."""
    return f"[{severity.value.upper().replace('_', ' ')}]"


def _generate_filename(prefix: str, extension: str) -> str:
    """Generate a timestamped filename for export."""
    ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return f"{prefix}_{ts}.{extension}"


# ===================================================================
# MAIN EXPORTER CLASS
# ===================================================================


class SCReportExporter:
    """Multi-format report exporter for the Single-Cell Intelligence Agent.

    Accepts analysis result objects (``WorkflowResult``, ``TMEProfile``, etc.)
    and produces reports in Markdown, JSON, PDF, and FHIR R4 formats.

    Usage::

        exporter = SCReportExporter()
        md = exporter.export_cell_type_report(annotations, sample_id="S-001")
        pdf_bytes = exporter.export_pdf(workflow_result)
        fhir = exporter.export_fhir_r4(workflow_result)
        anndata_meta = exporter.export_anndata_metadata(workflow_result)
    """

    # -- Cell Type Report --

    def export_cell_type_report(
        self,
        annotations: List[CellTypeAnnotation],
        sample_id: str = "DEMO",
    ) -> str:
        """Export a cell type annotation report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["cell_type"].format(
            sample_id=sample_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"**Total clusters annotated:** {len(annotations)}")
        lines.append("")

        if annotations:
            lines.append("## Cell Type Annotations\n")
            lines.append("| Cluster | Cell Type | Confidence | Markers | Fraction |")
            lines.append("|---------|-----------|------------|---------|----------|")
            for ann in annotations:
                markers = ", ".join(ann.marker_genes[:5])
                lines.append(
                    f"| {ann.cluster_id} | {ann.cell_type} | "
                    f"{ann.confidence.value} ({ann.confidence_score:.2f}) | "
                    f"{markers} | {ann.fraction:.1%} |"
                )
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- TME Report --

    def export_tme_report(
        self,
        profile: Union[TMEProfile, Dict[str, Any]],
        sample_id: str = "DEMO",
    ) -> str:
        """Export a TME profiling report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["tme"].format(
            sample_id=sample_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]

        if isinstance(profile, TMEProfile):
            lines.append(f"**TME Classification:** {profile.tme_class.value}")
            lines.append(f"**Immune Score:** {profile.immune_score:.2f}")
            lines.append(f"**Stromal Score:** {profile.stromal_score:.2f}")
            lines.append(f"**T Cell Exhaustion:** {profile.exhaustion_signature:.2f}")
            lines.append("")

            if profile.cell_type_fractions:
                lines.append("## Cell Type Composition\n")
                for ct, frac in sorted(
                    profile.cell_type_fractions.items(),
                    key=lambda x: x[1],
                    reverse=True,
                ):
                    lines.append(f"- **{ct}:** {frac:.1%}")
                lines.append("")

            if profile.checkpoint_expression:
                lines.append("## Checkpoint Expression\n")
                for gene, level in profile.checkpoint_expression.items():
                    lines.append(f"- **{gene}:** {level:.2f}")
                lines.append("")

            if profile.predicted_immunotherapy_response:
                lines.append(
                    f"## Predicted Immunotherapy Response: "
                    f"{profile.predicted_immunotherapy_response}\n"
                )
        elif isinstance(profile, dict):
            lines.append(f"**TME Classification:** {profile.get('tme_class', 'unknown')}")
            lines.append(f"**Immune Score:** {profile.get('immune_score', 0):.2f}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Drug Response Report --

    def export_drug_response_report(
        self,
        predictions: List[DrugResponsePrediction],
        sample_id: str = "DEMO",
    ) -> str:
        """Export a drug response prediction report as Markdown."""
        timestamp = _now_display()
        header = REPORT_TEMPLATES["drug_response"].format(
            sample_id=sample_id,
            timestamp=timestamp,
            version=VERSION,
        )

        lines: List[str] = [header]
        lines.append(f"**Drugs evaluated:** {len(predictions)}")
        lines.append("")

        if predictions:
            lines.append("## Drug Response Predictions\n")
            for pred in predictions:
                lines.append(f"### {pred.drug_name}")
                if pred.drug_class:
                    lines.append(f"**Class:** {pred.drug_class}")
                lines.append(f"**Predicted Sensitivity:** {pred.predicted_sensitivity:.2f}")
                lines.append(f"**Resistance Risk:** {pred.resistance_risk.value}")
                if pred.resistance_mechanisms:
                    lines.append(f"**Resistance Mechanisms:** {', '.join(pred.resistance_mechanisms)}")
                if pred.synergy_candidates:
                    lines.append(f"**Synergy Candidates:** {', '.join(pred.synergy_candidates)}")
                lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- Generic Markdown Export --

    def export_markdown(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        report_type: str = "workflow",
    ) -> str:
        """Export a generic workflow response as Markdown."""
        timestamp = _now_display()
        template_key = report_type if report_type in REPORT_TEMPLATES else "workflow"
        template = REPORT_TEMPLATES[template_key]

        header_vars: Dict[str, str] = {
            "timestamp": timestamp,
            "version": VERSION,
            "sample_id": "DEMO",
        }

        if isinstance(response, WorkflowResult):
            header_vars["workflow_type"] = response.workflow_type.value.replace(
                "_", " "
            ).title()
        else:
            header_vars["workflow_type"] = report_type.replace("_", " ").title()

        lines: List[str] = [template.format(**header_vars)]

        if isinstance(response, WorkflowResult):
            if response.cell_annotations:
                lines.append(f"## Cell Types Identified: {len(response.cell_annotations)}\n")
                for ann in response.cell_annotations[:10]:
                    lines.append(f"- **{ann.cell_type}** ({ann.confidence.value}): {ann.fraction:.1%}")
                lines.append("")
            if response.tme_profile:
                lines.append(f"## TME: {response.tme_profile.tme_class.value}\n")
            if response.drug_predictions:
                lines.append(f"## Drug Predictions: {len(response.drug_predictions)}\n")
        elif isinstance(response, dict):
            for key, val in response.items():
                if key not in ("workflow_type",):
                    lines.append(f"**{key}:** {val}")
            lines.append("")

        lines.append(_DISCLAIMER)
        return "\n".join(lines)

    # -- JSON Export --

    def export_json(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
    ) -> dict:
        """Export an analysis response as structured JSON."""
        if isinstance(response, WorkflowResult):
            data = response.model_dump()
        elif isinstance(response, dict):
            data = response
        else:
            data = {"raw": str(response)}

        return {
            "report_type": "single_cell_analysis",
            "generated_at": _now_iso(),
            "version": VERSION,
            "data": data,
        }

    # -- PDF Export --

    def export_pdf(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        title: str = "Single-Cell Intelligence Report",
    ) -> bytes:
        """Export an analysis response as a PDF document.

        Requires ``reportlab`` to be installed. Returns empty bytes if
        the dependency is not available.
        """
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import (
                SimpleDocTemplate,
                Paragraph,
                Spacer,
            )
            from reportlab.lib.styles import getSampleStyleSheet
        except ImportError:
            logger.warning(
                "reportlab not installed -- PDF export returning empty bytes"
            )
            return b""

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Title
        story.append(Paragraph(title, styles["Title"]))
        story.append(Spacer(1, 12))

        # Timestamp
        story.append(
            Paragraph(
                f"Generated: {_now_display()} | Version: {VERSION}",
                styles["Normal"],
            )
        )
        story.append(Spacer(1, 12))

        # Content
        if isinstance(response, WorkflowResult):
            story.append(
                Paragraph(
                    f"Workflow: {response.workflow_type.value}",
                    styles["Normal"],
                )
            )
            story.append(Spacer(1, 6))
            if response.cell_annotations:
                story.append(Paragraph("Cell Type Annotations:", styles["Heading2"]))
                for ann in response.cell_annotations[:15]:
                    story.append(
                        Paragraph(
                            f"{ann.cluster_id}: {ann.cell_type} "
                            f"({ann.confidence.value}, {ann.fraction:.1%})",
                            styles["Normal"],
                        )
                    )
                    story.append(Spacer(1, 4))
            if response.tme_profile:
                story.append(Paragraph(
                    f"TME Class: {response.tme_profile.tme_class.value}",
                    styles["Normal"],
                ))
                story.append(Spacer(1, 6))
        elif isinstance(response, dict):
            for key, val in response.items():
                story.append(
                    Paragraph(f"{key}: {val}", styles["Normal"])
                )
                story.append(Spacer(1, 4))

        # Disclaimer
        story.append(Spacer(1, 24))
        story.append(
            Paragraph(
                "Disclaimer: This report is for research and clinical "
                "decision-support only.",
                styles["Italic"],
            )
        )

        doc.build(story)
        return buffer.getvalue()

    # -- FHIR R4 Export --

    def export_fhir_r4(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
        patient_id: str = "DEMO",
    ) -> dict:
        """Export as a FHIR R4 DiagnosticReport Bundle."""
        report_id = str(uuid.uuid4())
        timestamp = _now_iso()

        if isinstance(response, WorkflowResult):
            conclusion_parts = []
            if response.cell_annotations:
                top_types = [a.cell_type for a in response.cell_annotations[:3]]
                conclusion_parts.append(f"Cell types: {', '.join(top_types)}")
            if response.tme_profile:
                conclusion_parts.append(f"TME: {response.tme_profile.tme_class.value}")
            conclusion = "; ".join(conclusion_parts) if conclusion_parts else ""
            category_code = response.workflow_type.value
        elif isinstance(response, dict):
            conclusion = str(response.get("summary", ""))
            category_code = response.get("workflow_type", "general")
        else:
            conclusion = str(response)
            category_code = "general"

        diagnostic_report = {
            "resourceType": "DiagnosticReport",
            "id": report_id,
            "status": "final",
            "category": [
                {
                    "coding": [
                        {
                            "system": "http://hcls-ai-factory.dev/sc-agent",
                            "code": category_code,
                            "display": category_code.replace("_", " ").title(),
                        }
                    ]
                }
            ],
            "code": {
                "coding": [
                    {
                        "system": "http://loinc.org",
                        "code": "94531-1",
                        "display": "Single-cell transcriptomic analysis",
                    }
                ]
            },
            "subject": {"reference": f"Patient/{patient_id}"},
            "effectiveDateTime": timestamp,
            "issued": timestamp,
            "conclusion": conclusion,
        }

        bundle = {
            "resourceType": "Bundle",
            "type": "document",
            "timestamp": timestamp,
            "entry": [
                {
                    "resource": diagnostic_report,
                    "fullUrl": f"urn:uuid:{report_id}",
                }
            ],
            "meta": {
                "profile": [
                    "http://hcls-ai-factory.dev/fhir/single-cell-intelligence-report"
                ],
                "tag": [
                    {
                        "system": "http://hcls-ai-factory.dev/version",
                        "code": VERSION,
                    }
                ],
            },
        }

        return bundle

    # -- AnnData Metadata Export --

    def export_anndata_metadata(
        self,
        response: Union[WorkflowResult, Dict[str, Any]],
    ) -> dict:
        """Export analysis results as AnnData-compatible metadata.

        Returns a dictionary suitable for storing in ``adata.uns`` or
        ``adata.obs`` columns in an AnnData/Scanpy workflow.

        Returns:
            Dict with keys like ``cell_type_annotations``, ``tme_profile``,
            ``agent_version``, ``generated_at``.
        """
        metadata: Dict[str, Any] = {
            "agent": "single_cell_intelligence_agent",
            "version": VERSION,
            "generated_at": _now_iso(),
        }

        if isinstance(response, WorkflowResult):
            metadata["workflow_type"] = response.workflow_type.value

            if response.cell_annotations:
                metadata["cell_type_annotations"] = {
                    ann.cluster_id: {
                        "cell_type": ann.cell_type,
                        "cell_ontology_id": ann.cell_ontology_id,
                        "confidence": ann.confidence.value,
                        "confidence_score": ann.confidence_score,
                        "marker_genes": ann.marker_genes,
                        "cell_count": ann.cell_count,
                        "fraction": ann.fraction,
                    }
                    for ann in response.cell_annotations
                }

            if response.tme_profile:
                metadata["tme_profile"] = {
                    "tme_class": response.tme_profile.tme_class.value,
                    "immune_score": response.tme_profile.immune_score,
                    "stromal_score": response.tme_profile.stromal_score,
                    "exhaustion_signature": response.tme_profile.exhaustion_signature,
                    "cell_type_fractions": response.tme_profile.cell_type_fractions,
                    "predicted_immunotherapy_response": response.tme_profile.predicted_immunotherapy_response,
                }

            if response.drug_predictions:
                metadata["drug_predictions"] = [
                    {
                        "drug_name": dp.drug_name,
                        "predicted_sensitivity": dp.predicted_sensitivity,
                        "resistance_risk": dp.resistance_risk.value,
                    }
                    for dp in response.drug_predictions
                ]

            if response.trajectories:
                metadata["trajectories"] = [
                    {
                        "trajectory_id": t.trajectory_id,
                        "type": t.trajectory_type.value,
                        "start": t.start_cell_type,
                        "end": t.end_cell_type,
                        "driver_genes": t.driver_genes,
                    }
                    for t in response.trajectories
                ]

            metadata["severity"] = response.severity.value

        elif isinstance(response, dict):
            metadata.update(response)

        return metadata
